// Generated by `supabase gen types typescript` in CI when the dev project is
// provisioned. Until then, this stub satisfies the `Database` generic that
// `@supabase/supabase-js` `createClient<Database>` expects.
//
// To regenerate locally once SUPABASE_DEV_DB_URL is set:
//   pnpm dlx supabase gen types typescript \
//     --db-url "$DATABASE_URL" \
//     --schema public > db/types.ts
//
// Drizzle (./schema.ts) is the authoritative typed schema for server code;
// this `Database` type powers the JS client's RLS-aware row types.

export type Database = Record<string, unknown>
